### ISSUE TITLE
images of posts (which also have text)

### ISSUE THREAD

**Issue by PurposeRefined1179** [chauduyphanvu/reddit-markdown#9]
Hey @chauduyphanvu , 
I tried this script today, it's great. 
In posts where there are both images and text, the link (see image below) generated in the file contains "&amp;" instead of just "&", hence giving the 403 forbidden page when clicked
<img width="548" alt="image" src="https://user-images.githubusercontent.com/120597920/224372713-80470594-50e2-4e51-9e96-6e3b0e896b1f.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/120597920/224373051-f1c697a9-f91b-4f03-8038-5d6db62b99bc.png">

Reddit post url provided to the program: 

https://www.reddit.com/r/ObsidianMD/comments/104k0om/script_save_reddit_posts_to_obsidian/

I am new on github (and new to programming js and rb), so I don't know if I am posting this in the right place, thanks!

**Comment by chauduyphanvu** [comment]
Hey, thanks for the report—you posted it to the right place :) I will take a look and circle back.

**Comment by chauduyphanvu** [comment]
Hello, I checked this out and it appears to be an issue from Reddit itself. If you download the post directly via the browser by appending `.json` to the post URL so that it is https://www.reddit.com/r/ObsidianMD/comments/104k0om/script_save_reddit_posts_to_obsidian/.json, you can see the JSON response contains that weird encoding issue already.

For example:

> https://preview.redd.it/qtl3p2hcjcaa1.png?width=2832&amp;format=png&amp;auto=webp&amp;v=enabled&amp;s=11b50f9134119a9bcbe7b29ce9477b873f0b79ae

Regardless, I've added additional safeguards for that in the v1.4.0 released in https://github.com/chauduyphanvu/reddit-markdown/releases/tag/1.4.0. Check it out and let me know if the issue persists!
